### ISSUE TITLE
Add `newtype` topic for better library discoverability

### ISSUE THREAD

**Issue by kaishh** [estatico/scala-newtype#12]
I finally found this lib which seems far better than alternatives https://github.com/alexknvl/newtypes , https://github.com/vitorsvieira/dilate , https://github.com/rudogma/scala-supertagged – but i found it accidentally even though I searched actively for ways to get newtypes in scala, adding a `newtype`, `tagged`, `tagged-types` tags might make it easier to discover the lib

**Comment by carymrobbins** [comment]
@kaishh Great idea! I added the following topics, feel free to let me know if some others might be useful as well.

* `newtype`
* `scala`
* `tagged`
* `tagged-types`
