### ISSUE TITLE
NewTypes with Type Parameters?

### ISSUE THREAD

**Issue by schlichtanders** [estatico/scala-newtype#2]
Is there a possibility to create a NewType for ``Seq[A]``?

``object`` unfortunately takes no typeparameters ...

**Comment by carymrobbins** [comment]
It's possible, but it requires some additional infrastructure which does not currently exist. I started experimenting with this in the [arity](https://github.com/estatico/scala-newtype/commits/arity) branch. Problem is currently we have to manually write out infrastructure for each case, and arity can get really complex.

For example, consider `Seq[A]`, `Map[K, V]`. We could handle each case up to some upper limit with code generation, but it gets more complicated when you deal with type parameters which themselves are higher kinded, e.g. `EitherT[F, A, B]`.

So your specific case _is_ possible, and the arity branch is a step towards it, problem is that this doesn't universally solve the "newtype for higher kinded types" problem. To handle those cases universally, it may require some newtype derivation via macros, which would also help alleviate the boilerplate for each and every case.

**Comment by carymrobbins** [comment]
This is now supported via the `@newtype` macro annotation.
